services:
  bg-api:
    image: josafaverissimo/boogie-woogie-pay:latest
    hostname: boogie-woogie-pay
    networks:
      - bg-api
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - X_RINHA_TOKEN=123
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

networks:
  bg-api:
    driver: bridge
  payment-processor:
    external: true
