services:
  bg-api-1: &bg-api
    image: josafaverissimo/boogie-woogie-pay:latest
    hostname: bg-api-1
    networks:
      - bg-api
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - X_RINHA_TOKEN=123
    depends_on:
      - valkey
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  bg-api-2:
    <<: *bg-api
    hostname: bg-api-2

  worker:
    image: josafaverissimo/boogie-woogie-pay-worker:latest
    hostname: bg-worker
    networks:
      - bg-api
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - X_RINHA_TOKEN=123
    depends_on:
      - valkey
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "35MB"

  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - bg-api
    depends_on:
      - bg-api-1
      - bg-api-2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"
  
  valkey:
    image: valkey/valkey:8.1.3-alpine
    ports:
      - "9927:6379"
    volumes:
      - bgpay-valkey-data:/data


networks:
  bg-api:
    driver: bridge
  payment-processor:
    external: true

volumes:
  bgpay-valkey-data:
